version: "3.8"
services:
  gym-app:
    build: .
    container_name: gym-fastapi-app
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - ./workflows/gym/templates:/app/workflows/gym/templates
      - ./workflows/gym/static:/app/workflows/gym/static
      - ./telegram/gym:/app/telegram/gym
    depends_on:
      - postgres_gymdb
    command: uvicorn workflows.gym.app_fastapi:app --host 0.0.0.0 --port=5050 --reload
    networks:
      - gym_network
      
  postgres_gymdb:
    image: postgres:17
    container_name: postgres_gymdb
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - gym_network
      
networks:
  gym_network:
    driver: bridge
    
volumes:
  postgres_data: